---
name: jupiter
description: Opinionated bootc distro.

base-image: ghcr.io/blue-build/base-images/fedora-kinoite-nvidia-open
image-version: latest 

modules:
  - type: files
    files:
      - source: system
        destination: /
        
  - type: initramfs 
  
  - type: os-release
    properties:
      ID: jupiter
      NAME: Jupiter
      PRETTY_NAME: Jupiter
      
  - type: dnf
    repos:
      nonfree: negativo17
      files:
        - https://brave-browser-rpm-release.s3.brave.com/brave-browser.repo
    install:
      packages:
        - brave-origin
        - steam
        - https://vencord.dev/download/vesktop/amd64/rpm
        - https://github.com/wimpysworld/sidra/releases/download/1.1.1/Sidra-1.1.1-linux-x86_64.rpm
    remove:
      packages:
        - firefox
        - firefox-langpacks 
        
  - type: default-flatpaks
    configurations:
      - notify: false
        scope: system
        install: 
          - org.vinegarhq.Sober
      - scope: user

  - type: signing
