---
name: jupiter
description: Opinionated bootc distro.

base-image: ghcr.io/ublue-os/kinoite-main
image-version: latest 

modules:
  - type: files
    files:
      - source: system
        destination: /
        
  - type: initramfs
  
  - type: akmods
    install: []
    nvidia-driver: nvidia-open
    
  - type: os-release
    properties:
      ID: jupiter
      NAME: Jupiter
      PRETTY_NAME: Jupiter
      
  - type: dnf
    repos:
      copr: 
        - g3tchoo/prismlauncher
      nonfree: negativo17
      files:
        - https://brave-browser-rpm-release.s3.brave.com/brave-browser.repo
    install:
      packages:
        - brave-origin
        - steam
        - https://vencord.dev/download/vesktop/amd64/rpm
        - prismlauncher
    remove:
      packages:
        - firefox
        - firefox-langpacks 
        
  - type: default-flatpaks
    configurations:
      - notify: false
        scope: system
        install: 
          - org.vinegarhq.Sober
      - scope: user

  - type: signing
